# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76910148d3d65ede9c3c63cbb60b1e1b7d455632d158eb7b7f6415a9f097e6e90046f30085ef54a8ce86719ebb9c59cadf9afd7b8ed22b2f689817e7716bbf22

test:
  secret_key_base: 1f0f5693dc6ea621965b2a35e8766d8a274635093e5318cfe5e45e5b54147d43dab68e15593f41751751684d8fa62d953fa58bda609bd21166a1fdd5ffb5f13a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
